version: 2

project_name: whitespace-tools

before:
  hooks:
    - go mod tidy
    - go generate ./...

git:
  tag_sort: -version:creatordate # enforces SemVer precedence first, then uses tag creation time to break ties
  prerelease_suffix: "-"

builds:
  # newline CLI tool
  - id: newline
    main: ./cmd/newline
    binary: newline
    tool: tinygo
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X main.version={{ .Version }}
      - -X main.commit={{ .Commit }}

  # trailingspace CLI tool
  - id: trailingspace
    main: ./cmd/trailingspace
    binary: trailingspace
    tool: tinygo
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X main.version={{ .Version }}
      - -X main.commit={{ .Commit }}

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - typo
      - minor

# GitHub release configuration
release:
  github:
    owner: scottrigby
    name: whitespace-tools
  name_template: "Release {{.Version}}"
  prerelease: auto

# Homebrew cask (for distributing prebuilt binaries)
homebrew_casks:
  - repository:
      owner: scottrigby
      name: homebrew-tap
    name: whitespace-tools
    description: CLI tools to fix Git whitespace issues
    homepage: "https://github.com/scottrigby/whitespace-tools"
    license: Apache-2.0
    binaries:
      - newline
      - trailingspace
    skip_upload: auto
