version: 2

project_name: newline

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  # Optimized Go build
  - id: "go-build"
    main: ./cmd/newline
    binary: newline
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -buildid=
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - typo
      - minor

# GitHub release configuration
release:
  github:
    owner: scottrigby
    name: newline
  name_template: "Release {{.Version}}"

# Homebrew cask (for distributing prebuilt binaries)
homebrew_casks:
  - repository:
      owner: scottrigby
      name: homebrew-tap
    name: newline
    description: "CLI tool to ensure files end with exactly one newline"
    homepage: "https://github.com/scottrigby/newline"
    license: "MIT"
